name: NiceTry
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      test:
        - run: make setup
        - script: make test
        - script: make lint
